name: dmpc
channels:
  - conda-forge
  - robostack-humble
  - defaults
dependencies:
  - ampl-asl=1.0.0=h286801f_2
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - casadi=3.7.0=py314h10cf2d5_5
  - contourpy=1.3.3=py314h784bc60_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.14.1=hce30654_0
  - icu=75.1=hfee45f7_0
  - ipopt=3.14.19=hd6b6db2_1
  - kiwisolver=1.4.9=py314h42813c9_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=2_h51639a9_openblas
  - libblasfeo=0.1.4.2=h37ef02a_0
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=2_hb0561ab_openblas
  - libcxx=21.1.6=hf598326_0
  - libdeflate=1.25=hc11a715_0
  - libexpat=2.7.3=haf25636_0
  - libfatrop=0.0.4=h286801f_1
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_12
  - libgfortran=15.2.0=h07b0088_12
  - libgfortran5=15.2.0=hdae7583_12
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=2_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libosqp=1.0.0=np2py313hd6693e2_2
  - libpng=1.6.51=hfab5511_0
  - libqdldl=0.1.8=ha1acc90_1
  - libscotch=7.0.10=int64_ha305a69_2
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.6=h4a912ad_0
  - matplotlib=3.10.8=py314he55896b_0
  - matplotlib-base=3.10.8=py314hd63e3f0_0
  - metis=5.1.0=h15f6cfe_1007
  - mumps-include=5.8.1=h2ca763e_4
  - mumps-seq=5.8.1=he6ca4b8_4
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - numpy=2.3.5=py314h5b5928d_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pillow=12.0.0=py314he16ad10_1
  - pip=25.3=pyh145f28c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.14.0=h40d2674_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.14=8_cp314
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - six=1.17.0=pyhe01879c_1
  - tinyxml2=11.0.0=ha1acc90_0
  - tk=8.6.13=h892fb3f_3
  - tornado=6.5.2=py314h0612a62_2
  - tzdata=2025b=h78e105d_0
  - unicodedata2=17.0.0=py314h0612a62_1
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - zlib-ng=2.2.5=h3470cca_0
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/miniconda3/envs/dmpc
